language: java

jdk:
  - oraclejdk8

install: true
before_install:
  - chmod +x travis/*.sh
script: ./travis/install.sh
env:
  global:
    - PUBLISH_BRANCH="mvn-repo"
    - DEPLOY_KEY_ID="1645300b04d0"

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  skip_cleanup: true
  on:
    tags: true
  file:
    - "build/repo/argelbargel/gradle/plugins/build-modules/$TRAVIS_TAG/build-modules-$TRAVIS_TAG.jar"
    - "build/repo/argelbargel/gradle/plugins/build-modules/$TRAVIS_TAG/build-modules-$TRAVIS_TAG.jar.md5"
    - "build/repo/argelbargel/gradle/plugins/build-modules/$TRAVIS_TAG/build-modules-$TRAVIS_TAG.jar.sha1"

cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper
